services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: ignite-call-pg
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: ignite-call
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

